version: "3"
services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
    environment:
      KEY: "cjkyJHfxAoo8iz#3z?frERiLFcMaxaC$XYtNKyiG"
      SECRET: "C66@C4n&rk4ke88m5RM&mGYzLH&XsrPMke9AiK!L"
      ADMIN_EMAIL: "yasminsdcastro@gmail.com"
      ADMIN_PASSWORD: "d1r3ctu5Party"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: true
